-- animations/LimeFrenzy.lua
-- Curves
hl.curve("default", { type = "bezier", points = { { 0.12, 0.92 }, { 0.08, 1.0 } } })
hl.curve("wind", { type = "bezier", points = { { 0.12, 0.92 }, { 0.08, 1.0 } } })
hl.curve("overshot", { type = "bezier", points = { { 0.18, 0.95 }, { 0.22, 1.03 } } })
hl.curve("liner", { type = "bezier", points = { { 2, 2 }, { 2, 2 } } })
hl.curve("md3_standard", { type = "bezier", points = { { 0.2, 0 }, { 0, 1 } } })
hl.curve("md3_decel", { type = "bezier", points = { { 0.05, 0.7 }, { 0.1, 1 } } })
hl.curve("md3_accel", { type = "bezier", points = { { 0.3, 0 }, { 0.8, 0.15 } } })
hl.curve("crazyshot", { type = "bezier", points = { { 0.1, 1.5 }, { 0.76, 0.92 } } })
hl.curve("hyprnostretch", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.0 } } })
hl.curve("menu_decel", { type = "bezier", points = { { 0.1, 1 }, { 0, 1 } } })
hl.curve("menu_accel", { type = "bezier", points = { { 0.38, 0.04 }, { 1, 0.07 } } })
hl.curve("easeInOutCirc", { type = "bezier", points = { { 0.85, 1 }, { 0.65, 1 } } })
hl.curve("easeOutCirc", { type = "bezier", points = { { 0, 0.55 }, { 0.45, 1 } } })
hl.curve("easeOutExpo", { type = "bezier", points = { { 0.16, 1 }, { 0.3, 1 } } })
hl.curve("softAcDecel", { type = "bezier", points = { { 0.26, 0.26 }, { 0.15, 1 } } })

-- Animations
hl.animation({ leaf = "windows", enabled = true, speed = 8.5, bezier = "wind", style = "popin 60%" })
hl.animation({ leaf = "windowsIn", enabled = true, speed = 8.5, bezier = "easeInOutCirc" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 8.5, bezier = "easeInOutCirc" })
hl.animation({ leaf = "windowsMove", enabled = true, speed = 4.5, bezier = "softAcDecel", style = "slide" })
hl.animation({ leaf = "layers", enabled = true, speed = 4, bezier = "easeOutCirc", style = "popin" })
hl.animation({ leaf = "fadeIn", enabled = true, speed = 7, bezier = "easeOutCirc" })
hl.animation({ leaf = "fadeOut", enabled = true, speed = 12, bezier = "easeInOutCirc" })
hl.animation({ leaf = "fadeSwitch", enabled = true, speed = 7, bezier = "easeInOutCirc" })
hl.animation({ leaf = "fadeShadow", enabled = true, speed = 7, bezier = "easeInOutCirc" })
hl.animation({ leaf = "fadeDim", enabled = true, speed = 7, bezier = "easeInOutCirc" })
hl.animation({ leaf = "fadeLayers", enabled = true, speed = 7, bezier = "easeInOutCirc" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 3.5, bezier = "easeInOutCirc", style = "slidevert" })
hl.animation({ leaf = "border", enabled = true, speed = 1, bezier = "liner" })
hl.animation({ leaf = "borderangle", enabled = true, speed = 90, bezier = "liner", style = "loop" })
